# Trabalho 1 - Álgebra Linear Computacional
## Exercícios computacionais

In [ ]:
# Importação das bibliotecas necessárias
import numpy as np
from numpy.linalg import matrix_rank, norm
from scipy.linalg import null_space
import sympy as sp

print("Bibliotecas importadas com sucesso!")

Bibliotecas importadas com sucesso!


## Exercício 8

Gere 100 matrizes aleatórias $5 \times 5$ com entradas inteiras entre $-5$ e $5$.

Para cada matriz:

1. Calcule o posto.
2. Verifique se a matriz é invertível.
3. Registre a frequência de cada valor de posto.
4. Apresente: uma tabela de frequências.

**Sugestão:**

```python
np.random.randint(-5, 5, (5, 5))

In [ ]:
# Gerando as 100 matrizes aleatórias 5x5 (valores entre -5 e 5)

matrizes = np.random.randint(-5, 6, (5, 5))

print(matrizes)

[[[-1  0  2  1 -2]
  [ 0  2  3 -1 -3]
  [-4  5 -4 -3  5]
  [-1  5  0  4 -1]
  [ 3  0  1  1 -2]]

 [[-5 -3  0  5 -5]
  [-3 -4  1  0 -3]
  [ 4 -3  4 -5  4]
  [ 0  5  2  3  1]
  [ 3  0  5 -2 -1]]

 [[ 1  3  2 -2 -1]
  [ 4 -1 -3 -1 -4]
  [-3 -4  4 -5 -3]
  [ 1  4 -2  0  0]
  [ 2 -4 -5 -4  3]]

 ...

 [[-1 -1 -5  5  3]
  [ 4 -3  0  1 -4]
  [ 0  1  4 -4  3]
  [-4  4  0 -4 -5]
  [ 0 -3 -2 -3  2]]

 [[-3 -2  0  2 -4]
  [ 2 -5  0  1  1]
  [-4  2  2  4  1]
  [-5  4 -1 -5  3]
  [-2 -2  1  5  1]]

 [[ 5  1 -1  2  1]
  [ 3 -2  2  3  2]
  [-3 -3 -1  1  1]
  [ 4 -1  0  3  0]
  [ 4  3 -3  2  4]]]


In [ ]:
# Verificando a frequência de cada posto

freq_postos = pd.Series(postos).value_counts().sort_index()
print(freq_postos)

5    100
Name: count, dtype: int64


## Exercício 9 — Espaço Nulo e Soluções de Sistemas Lineares

Considere o sistema:

$$
Ax = b
$$

com

$$
A =
\begin{bmatrix}
1 & 2 & 1 \\
2 & 4 & 2 \\
1 & 1 & 0
\end{bmatrix}
\quad \text{e} \quad
b =
\begin{bmatrix}
1 \\
2 \\
1
\end{bmatrix}
$$

1. Calcule o espaço nulo de $A$.
2. Resolva o sistema.

Verifique se o sistema possui:

- solução única  
- infinitas soluções  
- nenhuma solução

In [ ]:
# Definindo as matrizes A e b para os cálculos seguintes
A = np.array([[1, 2, 1], [2, 4, 2], [1, 1, 0]])
b = np.array([[1], [2], [1]])

print("Matriz A:")
print(A)
print("\nMatriz b:")
print(b)

Matriz A:
[[1 2 1]
 [2 4 2]
 [1 1 0]]

Matriz b:
[[1]
 [2]
 [1]]


In [ ]:
#1. Calculando o espaço nulo de A
# Para calcular o espaço nulo de uma matriz A, podemos usar a função null_space do scipy.linalg
# que retorna uma base para o espaço nulo da matriz.
espaco_nulo_A = null_space(A)
print("\nEspaço nulo de A:")
print(espaco_nulo_A)


Espaço nulo de A:
[[ 0.57735027]
 [-0.57735027]
 [ 0.57735027]]


In [ ]:
#2. Resolvendo o sistema linear Ax = b
# Para resolver o sistema linear Ax = b, podemos usar a função solve do numpy.linalg
try:
    solucao = np.linalg.solve(A, b)
    print("\nSolução única do sistema Ax = b:")
    print(solucao)
except np.linalg.LinAlgError:
    print("\nO sistema Ax = b não tem solução única (pode ser indeterminado ou impossível).")


O sistema Ax = b não tem solução única (pode ser indeterminado ou impossível).


In [ ]:
# Descobrindo se o sistema é indeterminado ou impossível
# Para isso, podemos comparar o posto da matriz A com o posto da matriz aumentada [A | b]
matriz_aumentada = np.hstack((A, b))
posto_A = matrix_rank(A)
posto_aumentada = matrix_rank(matriz_aumentada)
print(f"\nPosto de A: {posto_A}")
print(f"Posto da matriz aumentada [A | b]: {posto_aumentada}")
if posto_A < posto_aumentada:
    print("O sistema é impossível (sem soluções).")
elif posto_A == posto_aumentada:
    print("O sistema é possível (tem soluções).")
else:
    print("O sistema é indeterminado (tem infinitas soluções).")


Posto de A: 2
Posto da matriz aumentada [A | b]: 2
O sistema é possível (tem soluções).


## Exercício 10

Gere dois vetores aleatórios em $\mathbb{R}^{10}$.

Calcule a distância entre eles usando:

- norma 1  
- norma 2  
- norma infinito  

Repita o experimento 100 vezes e compare os resultados médios.

Apresente:

- média das distâncias  
- desvio padrão  

Discuta: qual norma tende a produzir valores maiores?

## Exercício 11

Investigue empiricamente a seguinte questão:

**Qual é a probabilidade de uma matriz aleatória $n \times n$ ser singular?**

### Procedimento:

- Para $n = 2, 3, 4, 5, 6$
- Gere 1000 matrizes aleatórias
- Calcule quantas são singulares

### Apresente:

- gráfico: probabilidade × dimensão

### Discuta:

- o comportamento observado